# n = input("Enter the name: ")
# n1 = int(input("Enter the number: "))
# print(n * n1)
#company = 'Company name is TechsimPlus'
# print(company[7:11])
# print(company[-4:])
# print(company[0:11:2])
# print(company[1:11:2])
#print(company[::-1])
# ind = company.index('h')
# print(ind)
# x = input('Enter the name: ')
# ind = company.find(x)
# print(ind)
# print(company.lower())
# print(company.upper())
# print(company.title())
lst = [1, 2, 3, 4, 5, 6,'Hello', 7, 8, 9, 10]
# print(lst[:3])
# print(lst[::-1])
# print(lst[-4:])
# print(lst[6])
# print(lst[::2])
# lst.append(11)
# print(lst)
# lst.insert(5, 12)
# print(lst)
# lst.extend([13, 14, 15])
# print(lst)
# n = int(input('Enter the position: '))
# n1 = int(input('Enter the value: '))
# lst.insert(n,n1)
# print(lst)
# lst.remove('Hello')
# print(lst)
# a = lst.pop()
# print(a)
# print(lst)

pos = int(input('Enter the position: '))
val = int(input('Enter the value: '))
lst.pop(pos)
lst.insert(pos, val)
print(lst)